services:
  nestjs-app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/mangahybrid
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    container_name: webtoon-nestjs-server_final

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    container_name: mangahybrid_final

  redis:
    image: redis
    ports:
      - "6379:6379"
    container_name: redis_final

volumes:
  mongo-data:
    external:
      name: a71630607f98d1f3bc25643697fe9ed631d9f95cb6a96dfb48ffd1d9a1d10bd6